In [67]:
import pandas as pd
import requests

Link of dataset

https://www.inditex.com/es/quienes-somos/inditex-en-el-mundo?p_p_id=mapsportlet_WAR_mapsportlet&p_p_lifecycle=2&p_p_state=normal&p_p_mode=view&p_p_resource_id=getTiendasByPaisAndIdCadena&p_p_cacheability=cacheLevelPage&p_p_col_id=column-1&p_p_col_count=1&idPais=11&idCadena=1

In [68]:
raw = pd.read_json('./inditex-en-el-mundo.json')
raw.head()

,idTi,nomTi,idCad,idGrupCad,nomCad,numCalle,codPost,idPob,pob,reg,...,calle,numeroCalle,codigoPostal,idPoblacion,poblacion,region,nombrePais,telefono,abreviado,centroComercial
0,179,cord-la sierra,1,1,zara,S/N,14011,95,cordoba,andalucía,...,poeta emilio prados,S/N,14011,95,cordoba,andalucía,españa,+34 957277023,18179,la sierra
1,168,usu-urbil,1,1,zara,7,20170,112,usurbil,país vasco,...,txikierdi auzoa,7,20170,112,usurbil,país vasco,españa,+34 943376113,18168,urbil
2,39,mur-constitucion,1,1,zara,1,30008,195,murcia,murcia,...,de la constitucion,1,30008,195,murcia,murcia,españa,+34 968236628,18639,
3,78,val-nuevo centro,1,1,zara,2,46009,248,valencia,comunidad valenciana,...,pio xii,2,46009,248,valencia,comunidad valenciana,españa,+34 963476942,18678,nuevo centro
4,161,vall-constitucion,1,1,zara,2,47001,251,valladolid,castilla y leon,...,constitucion,2,47001,251,valladolid,castilla y leon,españa,+34 983337438,18161,

In [69]:
raw.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 328 entries, 0 to 327
Data columns (total 35 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   idTi               328 non-null    int64
 1   nomTi              328 non-null    object
 2   idCad              328 non-null    int64
 3   idGrupCad          328 non-null    int64
 4   nomCad             328 non-null    object
 5   numCalle           328 non-null    object
 6   codPost            328 non-null    int64
 7   idPob              328 non-null    int64
 8   pob                328 non-null    object
 9   reg                328 non-null    object
 10  nomPais            328 non-null    object
 11  tel                328 non-null    object
 12  st_itxloc          328 non-null    object
 13  abre               328 non-null    object
 14  centCom            328 non-null    object
 15  secSen             328 non-null    object
 16  secCab             328 non-null    object
 17  secNin             328 non-null    object
 18  recic              328 non-null    object
 19  store_itxlocation  328 non-null    object
 20  nombreCadena       328 non-null    object
 21  idTienda           328 non-null    int64
 22  nombreTienda       328 non-null    object
 23  idCadena           328 non-null    int64
 24  idGrupoCadena      328 non-null    int64
 25  calle              328 non-null    object
 26  numeroCalle        328 non-null    object
 27  codigoPostal       328 non-null    int64
 28  idPoblacion        328 non-null    int64
 29  poblacion          328 non-null    object
 30  region             328 non-null    object
 31  nombrePais         328 non-null    object
 32  telefono           328 non-null    object
 33  abreviado          328 non-null    object
 34  centroComercial    328 non-null    object
dtypes: int64(10), object(25)
memory usage: 89.8+ KB

In [24]:
raw.columns

Index(['idTi', 'nomTi', 'idCad', 'idGrupCad', 'nomCad', 'numCalle', 'codPost',
       'idPob', 'pob', 'reg', 'nomPais', 'tel', 'st_itxloc', 'abre', 'centCom',
       'secSen', 'secCab', 'secNin', 'recic', 'store_itxlocation',
       'nombreCadena', 'idTienda', 'nombreTienda', 'idCadena', 'idGrupoCadena',
       'calle', 'numeroCalle', 'codigoPostal', 'idPoblacion', 'poblacion',
       'region', 'nombrePais', 'telefono', 'abreviado', 'centroComercial'],
      dtype='object')

In [56]:
raw['nombreTienda']

0           cord-la sierra
1                usu-urbil
2         mur-constitucion
3         val-nuevo centro
4        vall-constitucion
              ...
323    mad-parque corredor
324          mur-dos mares
325         mog-mogan mall
326       s.fern-bahia sur
327        sag-l'epicentre
Name: nombreTienda, Length: 328, dtype: object

In [47]:
location = raw['st_itxloc'].str.split(',', expand = True)
raw['latitude'] = location[0]
raw['longitude'] = location[1]
raw.head()

,idTi,nomTi,idCad,idGrupCad,nomCad,numCalle,codPost,idPob,pob,reg,...,codigoPostal,idPoblacion,poblacion,region,nombrePais,telefono,abreviado,centroComercial,latitude,longitude
0,179,cord-la sierra,1,1,zara,S/N,14011,95,cordoba,andalucía,...,14011,95,cordoba,andalucía,españa,+34 957277023,18179,la sierra,37.896226,-4.791112
1,168,usu-urbil,1,1,zara,7,20170,112,usurbil,país vasco,...,20170,112,usurbil,país vasco,españa,+34 943376113,18168,urbil,43.27613,-2.02497
2,39,mur-constitucion,1,1,zara,1,30008,195,murcia,murcia,...,30008,195,murcia,murcia,españa,+34 968236628,18639,,37.98974,-1.131916
3,78,val-nuevo centro,1,1,zara,2,46009,248,valencia,comunidad valenciana,...,46009,248,valencia,comunidad valenciana,españa,+34 963476942,18678,nuevo centro,39.48078918,-0.39069443
4,161,vall-constitucion,1,1,zara,2,47001,251,valladolid,castilla y leon,...,47001,251,valladolid,castilla y leon,españa,+34 983337438,18161,,41.651226,-4.7269

In [65]:
data = []

for i in raw.index:
    Name = raw.loc[i, 'nomTi'],
    Chain = raw.loc[i, 'nomCad']
    Street = raw.loc[i, 'calle'] 
    City = raw.loc[i, 'pob'] 
    Region = raw.loc[i, 'reg']
    Section = raw.loc[i, 'secSen'] + ', ' + raw.loc[i, 'secCab'] + ', ' + raw.loc[i, 'secNin']
    C_c = raw.loc[i, 'centCom']
    Latitude = raw.loc[i, 'latitude']
    Longitude = raw.loc[i, 'longitude']    
    
    data.append([Name, Chain, Street, City, Region, Section, C_c, Latitude, Longitude])
    
column = ['Name', 'Chain', 'Street', 'City', 'Region', 'Section', 'C_c', 'Latitude', 'Longitude']
zara = pd.DataFrame(data, columns = column)
zara.head()

,Name,Chain,Street,City,Region,Section,C_c,Latitude,Longitude
0,"(cord-la sierra,)",zara,poeta emilio prados,cordoba,andalucía,"Señora, Caballero, Niño",la sierra,37.896226,-4.791112
1,"(usu-urbil,)",zara,txikierdi auzoa,usurbil,país vasco,"Señora, Caballero, Niño",urbil,43.27613,-2.02497
2,"(mur-constitucion,)",zara,de la constitucion,murcia,murcia,"Señora, Caballero,",,37.98974,-1.131916
3,"(val-nuevo centro,)",zara,pio xii,valencia,comunidad valenciana,"Señora, Caballero, Niño",nuevo centro,39.48078918,-0.39069443
4,"(vall-constitucion,)",zara,constitucion,valladolid,castilla y leon,"Señora, ,",,41.651226,-4.7269

In [66]:
zara.to_csv('./zara.csv', index = False)